### ISSUE TITLE
Archivos separados

### ISSUE THREAD

**Issue by jorgeemherrera** [JoseHerrera240/JavaScriptCesde#1]
https://github.com/JoseHerrera240/JavaScriptCesde/blob/3537f5bddfb267a026ae46cd30978156753e0650/jsmoderno1.html#L11

**Comment by jorgeemherrera** [comment]
Porfa separa todos esos javascript de los html, y los referencias, para yo poder revisarlos

**Comment by jHerrera240** [comment]
Jorge, listos los cambios, gracias.
